# Generated by Django 4.2.7 on 2023-12-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_remove_profile_creation_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="recipe",
            new_name="used_in",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipeingredient",
            ),
            preserve_default=False,
        ),
    ]
