# Generated by Django 4.2.7 on 2023-12-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_rename_recipe_recipeingredient_used_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(to="recipes.recipeingredient"),
        ),
    ]
