# Generated by Django 4.1.12 on 2023-10-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tag_remove_recipe_recipe_type_rename_author_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_type',
        ),
    ]
