# Generated by Django 4.2.7 on 2023-12-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_profile_alter_comment_user_alter_recipe_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.profile"
            ),
        ),
    ]
